language: python
python:
- 2.7
- 3.6
install:
- make install
script:
- make coverage
after_success:
- coveralls
deploy:
  provider: pypi
  user: kirill.konshin
  password:
    secure: $PYPI_TOKEN
  on:
    python: 2.7
    tags: true
    repo: ringcentral/ringcentral-python
    branch: master
